<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\User;

class Season4StudentData extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $first = User::Create(["Name"=>"A Najmah As Anna","email"=>"annairfan77@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285876680800","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Afziah Lisayenti","email"=>"hanihaya1221@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282110793988","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ambar Mardatilla","email"=>"ambar_illa17@yahoo.co.id","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281379301987","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Amelia Yustika","email"=>"purbasari0882@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282245331113","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ana Mulyanah","email"=>"anamulyanah20@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281220069938","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Anatriyeni","email"=>"Anayeni02@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281247885328","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Andita Mandasari","email"=>"anditamanda@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628111201812","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Anne Ramdhaniati Yuliantine","email"=>"anneramdhaniati@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281322629699","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ansheila Pramudwithya","email"=>"sila.ansheila@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6287877195566","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Arie Pratama","email"=>"ariepratama765@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281256598507","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Arlinda Kusuma","email"=>"arkuszayn@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282291383607","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Arum Setyowati","email"=>"arum.kusumo.73@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281319960616","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Asmaniaty","email"=>"cali4nia19@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281367424784","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ayesha Rachma Hardiyani","email"=>"ay35ha.echa@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281122330220","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ayu Purnamasasi","email"=>"purnamasari10ayu@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628972107968","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ch.Fitria Atmakusumawati","email"=>"ch.fitria1978@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281328657753","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Christi Fauliani","email"=>"christi5847@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281210555464","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Chusnul","email"=>"chusnulchotimah1015@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6283115233740","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Chusnul Chotimah","email"=>"c.chotimah77@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628123223121","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Darwati","email"=>"dwidarwati519@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"62895367460264","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Dede Siti Aminah","email"=>"d3d3sa@yahoo.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6287831001800","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Denny Ferlina","email"=>"dennyferlina@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285711116097","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Desi Rianti","email"=>"desi.rianti12@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281391568310","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Desi Susanti","email"=>"desisusanti81@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628112053311","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Devi Amalia Putri","email"=>"amaliadevi902@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282164591403","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Dewi Wijayanti","email"=>"dewi.wijayanti27@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6287878223642","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Dhiya Nafi'ah","email"=>"dhiyanafiah24@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281310681935","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Dian Purwanti","email"=>"dianpurwanti80@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628118075875","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Diana Dewi","email"=>"Fatihzumar@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285717518588","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Dinda Sarika","email"=>"dindasarika17@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281315564566","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Dini Alifia","email"=>"dinialifia96.da@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281218293032","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Dini Soetadi","email"=>"antinayogy@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628119532900","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Dinni Kurniasari","email"=>"novalistin@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281313790700","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Dwi Endang Setya Rini","email"=>"dwiendang476@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6289618625930","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Dwi Purnama Sari","email"=>"saridp25@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281266575313","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Dwiretno Wijiastuti","email"=>"retiwari@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6283895233934","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Dyan Fatmawati Yusuf","email"=>"dyan.fatmawati86@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281225183720","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Efa Maria Ulfa","email"=>"efamariquu@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285323035313","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Eka Mustika Sari","email"=>"ekams.rustam@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6289630497577","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Elvi Sukma","email"=>NULL,"password"=>bcrypt('sekolah7ps4'),"phone"=>"6282391775466","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Eramayawati","email"=>"eramayawati@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285260222032","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Erly Zuliana","email"=>"early.candy@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281316280970","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Estri Wirandawi","email"=>"estriwirandawi@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281380907469","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Euis Afriany","email"=>"jumalieuis@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628551758892","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Eva Silviana Futikha","email"=>"evasilviana786@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281326151782","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Evi Susanti","email"=>"evisusanti21331@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281388112608","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Fadillah","email"=>"fadillahbiru@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281373553456","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Fadlika Isna Maisyaroh","email"=>"fadlikauus@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"62895623051994","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Faqihah","email"=>"boyoffice@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281584143057","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Febtarini Rahmawati","email"=>"febtapatklin@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281703875858","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ferisah Ita Maryani","email"=>"ferisah23februari@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281383190150","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Fitria Rihu","email"=>"fitria.rihu@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282344597901","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Frenciyani","email"=>"frenciyani.salim@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281354985866","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ghina Septiandani","email"=>"ghina.gimess@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628976582702","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Gina Anggaretna","email"=>"g1n4aliya@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281346279966","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Gina Triana","email"=>"ginatriana_ssi@yahoo.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281274398880","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Gita Astagina","email"=>"gitastagina@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281322015677","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Hafisah Dawi","email"=>"hafisadawi@ymail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281354607702","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Hamidah Althaf","email"=>"hamidahalthaf06@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"62895617755978","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Hana Mujahidah","email"=>"hanamjhdh@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282165596322","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Hasna Mahmudah","email"=>"oppoherman786@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281263027735","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Henny Fauziah","email"=>"hefau10@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285814603752","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Heny Suhaeny","email"=>"cv.upplus.indo@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285230856232","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Herin Setianingsih","email"=>"herin.setianingsih@hangtuah.ac.id","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281232555576","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Hidayati Zainuddin","email"=>"ummi_azim@icloud.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282397550895","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Hikma","email"=>"hikmayusuf@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"62818241474","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Hiusakirani","email"=>"husakuraniviral68@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281524517059","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Hj.Nurlian","email"=>"nurliansarif01@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285348359073","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Icha Liara Gusti","email"=>"icha5800@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282279512180","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ida Nuryani","email"=>"fashionhanshop@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281222666037","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Iis Masrohah","email"=>"iismasrohah28@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285524875520","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Iis Ratnawati","email"=>"ratnawatiiis19@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6287802772533","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ika Rahma Yanti","email"=>"ikarahmayanti45@yahoo.co.id","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282332424005","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ika Sulistyaningrum Hapsari","email"=>"sulistyaningrumhapsari@yahoo.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281329115840","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Imanda Amalia","email"=>"aisyah14r@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285779563224","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Indra Yanti","email"=>"dr.indrayanti@yahoo.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281277389658","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Irma Lisa Sridanti","email"=>"irmalisa2010@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282184419987","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Isna Rahanis","email"=>"isna.rahanis1010@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281267125371","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Isnawati","email"=>"isnasyafri@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281355582752","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Kastun","email"=>"kastun07@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281249671799","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Khairunnisyah Siregar","email"=>"ichasafril95@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281214818199","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Komawati","email"=>"komawatiasraf@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285288812112","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Leli Juliarti","email"=>"leli.juliarti@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628125614174","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Libriyanti Umul Chasanah","email"=>"libriyanti_111@yahoo.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285338532349","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Lisnawati","email"=>"farzanahalula295@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628179178134","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Lufita Nur Ainis","email"=>"lufitanurainis@gmail.com.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285814670646","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Marina Saputri","email"=>"marinasaputri2014@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281311004026","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Maulina","email"=>"lynadidid@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"62818299989","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Mega Putri Aulia","email"=>"mgwd4ever_love@yahoo.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628119042777","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Miga Mutiara","email"=>"migamutiara9@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285213616298","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Milda Anggraini, Am.Keb","email"=>"mildaanggraini6@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282281011278","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Molli Ra","email"=>"molli.rahmina@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628119770136","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Monike Hartanti","email"=>"monikehartanti@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281386489777","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Moresi Alfathonah","email"=>"moresialfathonah87@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282289080937","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Muliati Dolofu","email"=>"dolofumuliati@yahoo.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285241993653","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Mulyani","email"=>"mulyanimulyani0420@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628882829324","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Mulyanti","email"=>"zmulyanti@yahoo.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628125414183","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Musdalifa","email"=>"musdalifa.husain.ifa@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285237281389","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nadya Pratiwi","email"=>"nadya.p25@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628111802530","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nanik Wahyuningsih","email"=>"nanikwahyuningsih031@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285293644707","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nasliya","email"=>"azzahraizza@ymail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282145299286","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nelly Herliani","email"=>"herlianinelly16@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281280355603","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nena Sugiana","email"=>"nenasugiana29@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281809006445","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nenny Marhayani","email"=>"thenenny@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281286555535","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nita Fahrunnisa","email"=>"nita.fahrunnisa75@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6288811536566","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Noor Anita Rejeki","email"=>"salimsalam1724@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285821172007","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Norhayati","email"=>"hayatiehidayat@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282157957012","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Normawati","email"=>"normaskd7180@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281381219148","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Novie Hairani","email"=>"opieethey@yahoo.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281370522952","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Novina Aryanti","email"=>"novina.aryanti@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6287855698140","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Novita","email"=>"novita.fayra@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628123392620","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nur Fatimah","email"=>"nailahakifah3@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282250207930","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nur Kholifah","email"=>"nurkholifahc7@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6289509516764","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nur Sakinah","email"=>"sachinah12@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281331263390","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nurhaedah","email"=>"nurhaedahbundah81@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282188014625","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nurhalimah Dm","email"=>"nurhalimahdm21@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282390805133","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nurhayati","email"=>"nurhayatialiman@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285839856582","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nurizka Lubis","email"=>"nurizkalubis162122@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281398337988","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Nuryana Alinti","email"=>"nuryanahalinti@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285211088560","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ombah Hanipah","email"=>"ombahhanipah273@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282118339531","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Poppy","email"=>"poppyandanasari@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628118301757","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Puti Adani","email"=>"puti.adani@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6287886971024","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Putry Anggraeni Aly","email"=>"putry.aly88@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281932419604","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Rachmi Sumartini","email"=>"1965rachmi@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281399494093","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Rada Dwiyani","email"=>"rada.dwiyani@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285819073448","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Rani Yusup","email"=>"raniyusuf7@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281221919994","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Rasmin Pulu","email"=>"rasminpulu7@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282216462817","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ratih Elisa Nandarani","email"=>"ratihelisa79@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"62818387929","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Reni Andriani","email"=>"reni.a.muslih@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285773449349","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Reno Suri","email"=>"renoruzain@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281311129477","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Resti","email"=>"restideudeh@yahoo.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282299544706","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Retta Meditaria","email"=>"rettameditaria@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628111508698","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Reyhan Kasai","email"=>"reyhankasai@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628116889991","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ria Anggraini","email"=>"ria.anggraini@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628176493908","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ria Kurni","email"=>"Ririrhea@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"62811515697","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Riana","email"=>"rianamatanubun@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282234563221","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Rida Rosida","email"=>"rosida.rida@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6287821538663","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Rika Anggraini","email"=>"soviaz41@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285274666601","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Rika Rakhmalina","email"=>"rumah.khalina@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285609564556","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Rini Puji Lestari","email"=>"abc.aa990@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281359333616","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ririn Fitriana","email"=>"ririnfitriana2014@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281222687462","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Risna Agustina","email"=>"risnaagustina506@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282160589248","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Rivani Noor","email"=>"noorriva@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281286109813","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Rizki Maria Fransiska Agustina","email"=>"agustinak66@yahoo.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281233669664","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Rosmeiti","email"=>"meiti.andika@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628122958414","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Safrida Iryani","email"=>"idarawi75@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285357880355","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Septiyanti","email"=>"dewiyanti230981@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628129292691","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Silvia Anggraeni","email"=>"Silviaerwan@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281322227076","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Siti Julaikha","email"=>NULL,"password"=>bcrypt('sekolah7ps4'),"phone"=>"6281511325086","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Sofi Laila Oktavia","email"=>"sofi.oktavia.01@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6287877977376","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Sri Festyowati","email"=>"sri.festyo@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"62818990383","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Sri Handayani","email"=>"iaidil088@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285279756765","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Sri Melgiyanti","email"=>"ajenglala0@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282285801739","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Sri Rahayu Kadir","email"=>"srirahayukadir88@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281339084676","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Sri Wahyuni","email"=>"uni.budiluhur@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282119037768","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Sulistyawati","email"=>"sulisthadiwikarta@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628979107565","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Sunarti","email"=>"sunartikasman2010@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285394148830","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Surati/Ummu Aini","email"=>"Suratiaisyah@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282156377678","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Suryani","email"=>"susadsyah84@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6283891665130","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Suryani Alawiyah","email"=>"suryanialawiyah.sa@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282280802110","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Syifa Nur Fitria","email"=>"syifa.fitrianur@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281514060206","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Tien Ainurrohmi","email"=>"tienainurrohmi16@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281284023575","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Tina Yuhana","email"=>"rizafigiani2018@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6289656510285","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Tini Kartini","email"=>"tinik8216@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281321507509","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Tissa Ratna Kusumaningrum","email"=>"ordinaryperson1502@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281809024181","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Tri Atminingrum","email"=>"triatminingrum14@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281330163333","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Tri Marlianawati","email"=>"linasoekisno@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"62811856385","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Triwik Yulia Ningsih","email"=>"triwiky19@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"62895342297000","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Tuti Alawiyah","email"=>"alawiyah6581@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281287206810","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Tutut Syarifah","email"=>"syariuut@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281297268735","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ujianti Usman","email"=>NULL,"password"=>bcrypt('sekolah7ps4'),"phone"=>"6285230500587","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Umi Farida","email"=>"umifarida.kuta@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281999043030","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Ummu Tsalatsah","email"=>NULL,"password"=>bcrypt('sekolah7ps4'),"phone"=>"6281220067350","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Umraatin Indira Hussein","email"=>"umraatinindirah@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285694503544","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Venny Dwi Lestari","email"=>"vennydl87@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285697044198","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Virginia Ainurridlo Nugroho","email"=>"virginugroho@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285645200527","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Vivisantri","email"=>NULL,"password"=>bcrypt('sekolah7ps4'),"phone"=>"6285241303953","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Wa Ode Noni Indriani","email"=>"waodenoniindriani@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285210259702","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Wenni Ika Sari","email"=>"jairra2703@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6281331862156","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Wiji Suciari","email"=>"wijisuciari662@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285108453777","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Winarti Hapsari Hindiyana","email"=>"rafiibranana123@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285875143702","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Windy","email"=>"dmywindy@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6282122055499","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Wisda Widiastuti","email"=>"wisdawidiastuti11@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285263632898","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Yeni Nurhayati","email"=>"yeniedelaa23@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285780613148","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      User::Create(["Name"=>"Yuli Anggriyani","email"=>"yulleanggi@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"628990908444","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);
      $last = User::Create(["Name"=>"Yuliana","email"=>"yulibatam2021@gmail.com","password"=>bcrypt('sekolah7ps4'),"phone"=>"6285831115402","role_id"=>1,"multiple_courses"=>0,"default_course"=>4]);

      for ($i=$first->id; $i <= $last->id; $i++) { 
        DB::table('course_user')->insert(
          ['id'=>'4_'.$i,'user_id'=>$i, 'course_id'=>4]
        );
      }
    }
}
